#Configuration file

#Port can be found in the system tray menu or through Device Manager on windows.
ComPort: COM3
#Choose a volume from the list below. If none match what you want, edit or add to the list. This will update the options in the GUI menu too
VolumeSensitivity: 1
VolumeSensitivityOptions:
- 1
- 3
- 5
#Playback device can be selected through the menu. Default will listen to OS for device focus. 
#But if multiple audio devices are used, like mics and multiple speakers, specifying this will force the volume knob to control only that device
PlaybackDevice: Default Device
#Change this if you want the album artist displayed instead of the artist, or vice versa
AlbumArtist: false
#Change which programs Thoth's Oracle listens to. Case insenstive.
#If multiple are provided, their order represents their priority (top is first). Only the highest active program will be used.
#If none are provided or none listed are found, program will not listen to any. This is to prevent some programs that drop their sessions when changing tracks
MonitoredProgram:
- MusIcBEe.exe
- vlc.exe
- fireFOX.exe
#Wallpaper mode for cycling through images in Wallpapers folder
WallpaperMode: false
#How long before image changes in minutes
WallpaperPeriod: 5
#Display the following text when in wallpaper mode
WallpaperTitle: Wallpaper Mode
WallpaperAlbum: ' '
WallpaperArtist: ' '

#Nitty gritty tuning. These values should be good for most circumstances
#Speed is unused
Speed: 9600
WriteTimeout: 5000
ReadTimeout: 1000
ConnectionWait: 500
ReConnectionWait: 2000
MediaCheck: 500
ConfigCheck: 1000
OracleReadyWait: 1000
DisconnectedWait: 4000
LogContinuous: false
